routes/web.php
<?php

use App\Http\Controllers\AboutController;
use App\Http\Controllers\BlockController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SauceController;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',[PageController::class, 'home'])->name('home');
Route::get('/sauzen',[ProductController::class, 'index'])->name('product.index');
Route::get('/overmij', [AboutController::class, 'index'])->name('overmij');
Route::get('/sauzen/{sauce}', [ProductController::class, 'show'])->name('product.show');
Route::get('/contact', [ContactController::class, 'index'])->name('contact');


Route::post('/contact', [ContactController::class, 'store'])->name('contact.store');

Route::prefix('dashboard')->group(function () {

    Route::middleware(['auth'])->group(function () {

        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
        Route::get('/createpage', [DashboardController::class, 'create'])->name('create.page');

        Route::get('/createsauce', [SauceController::class, 'create'])->name('sauce.create');
        Route::post('/createsauce', [SauceController::class, 'store'])->name('sauce.store');

        Route::get('/edit/page/{page}', [DashboardController::class, 'edit'])->name('dashboard.edit');
        Route::get('/edit/sauzen/{sauce}', [SauceController::class, 'edit'])->name('sauce.edit');

        Route::put('/edit/page/{page}', [DashboardController::class, 'update'])->name('page.update');
        Route::put('/edit/sauzen/{sauce}', [SauceController::class, 'update'])->name('sauce.update');


        Route::post('/createpage', [DashboardController::class, 'store'])->name('page.store');
        Route::delete('/delete/page/{page}', [DashboardController::class, 'delete'])->name('page.delete');
        Route::delete('/delete/contact/{contact}', [ContactController::class, 'delete'])->name('contact.delete');

        Route::get('/page/{block}', [DashboardController::class, 'show'])->name('page.edit');


        Route::put('/page/{block}', [BlockController::class, 'update'])->name('block.update');
        Route::post('/page/{page}/store', [BlockController::class, 'store'])->name('block.store');
    });
});

// Route::get('/dashboard', function () {
    //     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Block;
use App\Models\Contact;
use App\Models\Page;
use Illuminate\Http\Request;

class DashboardController extends Controller
{

    public function create(){
        return view('createpage');
    }

    public function index(){

        $pages = Page::get();
        $contacts = Contact::latest()->get();


        return view('dashboard.index', [
            'pages' => $pages,
            'contacts' => $contacts,
        ]);
    }
    // public function show($id){

    //     $page = Page::findOrFail($id);

    //     return view('page.show', [
    //         'page' => $page,
    //     ]);
    // }

    public function show($block){

        $block = Block::findOrFail($block);

        return view('dashboard.show', [
            'block' => $block,
        ]);
    }

    public function edit($page){

        $page = Page::find($page);

        return view('dashboard.edit', [
            'page' => $page,
        ]);
    }

    public function update(Request $request, $page){

        Page::where('id', $page)->update([
            'page_title' => $request->page_title,
            'meta_keywords' => $request->meta_keywords,
            'meta_description' => $request->meta_description,
            'meta_title' => $request->meta_title,
        ]);

        return redirect()->route('dashboard');

    }


    public function delete(Page $page){

        $page->delete();

        return redirect()->route('dashboard');
    }

    public function store(Request $request){

        //validation for form
        $this->validate($request, [
            'page_title' => 'required|max:255',
        ]);

        Page::create([
            'page_title' => $request->page_title,
            'meta_keywords' => $request->meta_keywords,
            'meta_description' => $request->meta_description,
            'meta_title' => $request->meta_title,
        ]);

        return redirect()->route('dashboard');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/dashboard/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <div class="flex items-center h-screen w-full bg-teal-lighter">
                        <div class="w-full bg-white rounded shadow-lg p-8 m-4">
                          <h1 class="text-3xl font-bold text-lg block w-full text-center text-grey-darkest mb-6">Wijzig een Pagina</h1>

                          <form class="mb-4" action="{{ route('page.update', $page->id) }}" method="POST">

                            @method('put')
                            @csrf

                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="page_title">Pagina Titel</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="text" value="{{$page->page_title}}" name="page_title">
                            </div>
                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="meta_keywords">Keywords</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="text" value="{{$page->meta_keywords}}" name="meta_keywords">
                            </div>
                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="meta_description">Description</label>
                              <textarea class="border py-2 px-3 text-grey-darkest" name="meta_description" cols="30" rows="5">{{ $page->meta_description }}</textarea>
                            </div>
                            <div class="flex flex-col mb-6">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="meta_title">Meta Title</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="text" value="{{$page->meta_title}}" name="meta_title">
                            </div>
                            <button type="submit" class="w-full h-12 px-6 text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800">Wijzig pagina info</button>
                          </form>

                        </div>
                      </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/dashboard/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">


                <div class="p-6 bg-white border-b border-gray-200">

                    <table class="min-w-max w-full table-auto mb-4">
                        <thead>
                            <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                                <th class="py-3 px-6 text-left">Pagina titel</th>
                                <th class="py-3 px-6 text-left">Meta titel</th>
                                <th class="py-3 px-6 text-center">Status</th>
                                <th class="py-3 px-6 text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="text-gray-600 text-sm font-light">
                            @foreach ($pages as $page )

                            <tr class="border-b border-gray-200 hover:bg-gray-100">
                                <td class="py-3 px-6 text-left whitespace-nowrap">
                                    <div class="flex items-center">
                                        <div class="mr-2">
                                            <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                                                 width="24" height="24"
                                                 viewBox="0 0 48 48"
                                                 style=" fill:#000000;">
                                                <path fill="#80deea" d="M24,34C11.1,34,1,29.6,1,24c0-5.6,10.1-10,23-10c12.9,0,23,4.4,23,10C47,29.6,36.9,34,24,34z M24,16	c-12.6,0-21,4.1-21,8c0,3.9,8.4,8,21,8s21-4.1,21-8C45,20.1,36.6,16,24,16z"></path><path fill="#80deea" d="M15.1,44.6c-1,0-1.8-0.2-2.6-0.7C7.6,41.1,8.9,30.2,15.3,19l0,0c3-5.2,6.7-9.6,10.3-12.4c3.9-3,7.4-3.9,9.8-2.5	c2.5,1.4,3.4,4.9,2.8,9.8c-0.6,4.6-2.6,10-5.6,15.2c-3,5.2-6.7,9.6-10.3,12.4C19.7,43.5,17.2,44.6,15.1,44.6z M32.9,5.4	c-1.6,0-3.7,0.9-6,2.7c-3.4,2.7-6.9,6.9-9.8,11.9l0,0c-6.3,10.9-6.9,20.3-3.6,22.2c1.7,1,4.5,0.1,7.6-2.3c3.4-2.7,6.9-6.9,9.8-11.9	c2.9-5,4.8-10.1,5.4-14.4c0.5-4-0.1-6.8-1.8-7.8C34,5.6,33.5,5.4,32.9,5.4z"></path><path fill="#80deea" d="M33,44.6c-5,0-12.2-6.1-17.6-15.6C8.9,17.8,7.6,6.9,12.5,4.1l0,0C17.4,1.3,26.2,7.8,32.7,19	c3,5.2,5,10.6,5.6,15.2c0.7,4.9-0.3,8.3-2.8,9.8C34.7,44.4,33.9,44.6,33,44.6z M13.5,5.8c-3.3,1.9-2.7,11.3,3.6,22.2	c6.3,10.9,14.1,16.1,17.4,14.2c1.7-1,2.3-3.8,1.8-7.8c-0.6-4.3-2.5-9.4-5.4-14.4C24.6,9.1,16.8,3.9,13.5,5.8L13.5,5.8z"></path><circle cx="24" cy="24" r="4" fill="#80deea"></circle>
                                            </svg>
                                        </div>
                                        <a href="{{ route('dashboard.edit', [$page->id]) }}">
                                            <span class="font-medium">{{ $page->page_title }}</span>
                                        </a>
                                    </div>
                                </td>
                                <td class="py-3 px-6 text-left">
                                    <div class="flex items-center">
                                        <a href="{{ route('dashboard.edit', [$page->id]) }}">
                                            <span>{{ $page->meta_title }}</span>
                                        </a>
                                    </div>
                                </td>

                                <td class="py-3 px-6 text-center">
                                    <span class="bg-purple-200 text-purple-600 py-1 px-3 rounded-full text-xs">Active</span>
                                </td>
                                <td class="py-3 px-6 text-center">
                                    <div class="flex item-center justify-center">

                                        <a href="{{ route('page.edit', [$page->id]) }}">
                                            <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                                </svg>
                                            </div>
                                        </a>

                                        <a href="{{ route('page.edit', [$page->id]) }}">
                                            <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                                </svg>
                                            </div>
                                        </a>

                                        <form action="{{ route('page.delete', [$page->id]) }}" method="post">
                                            @csrf
                                            @method('DELETE')

                                            <button class="outline-none border-none" type="submit">
                                                <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                    </svg>
                                                </div>

                                            </button>
                                        </form>


                                    </div>
                                </td>
                            </tr>

                            @endforeach



                        </tbody>
                    </table>


                    <button class="w-full h-12 px-6 text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800"><a href="{{ route('create.page') }}">Pagina Toevoegen</a></button>
                </div>


            </div>
        </div>
    </div>


    <div class="py-12">


        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">


                <div class="p-6 bg-white border-b border-gray-200">

                    <h1 class="text-4xl font-bold mb-4">Berichten</h1>
                    <table class="min-w-max w-full table-auto mb-4">
                        <thead>
                            <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                                <th class="py-3 px-6 text-left">Naam</th>
                                <th class="py-3 px-6 text-left">Email</th>
                                <th class="py-3 px-6 text-center">Telefoonnummer</th>
                                <th class="py-3 px-6 text-center">Bericht</th>
                                <th class="py-3 px-6 text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="text-gray-600 text-sm font-light">
                            @foreach ($contacts as $contact )

                            <tr class="border-b border-gray-200 hover:bg-gray-100">
                                <td class="py-3 px-6 text-left whitespace-nowrap">
                                    <div class="flex items-center">
                                        <div class="mr-2">
                                            <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                                                 width="24" height="24"
                                                 viewBox="0 0 48 48"
                                                 style=" fill:#000000;">
                                                <path fill="#80deea" d="M24,34C11.1,34,1,29.6,1,24c0-5.6,10.1-10,23-10c12.9,0,23,4.4,23,10C47,29.6,36.9,34,24,34z M24,16	c-12.6,0-21,4.1-21,8c0,3.9,8.4,8,21,8s21-4.1,21-8C45,20.1,36.6,16,24,16z"></path><path fill="#80deea" d="M15.1,44.6c-1,0-1.8-0.2-2.6-0.7C7.6,41.1,8.9,30.2,15.3,19l0,0c3-5.2,6.7-9.6,10.3-12.4c3.9-3,7.4-3.9,9.8-2.5	c2.5,1.4,3.4,4.9,2.8,9.8c-0.6,4.6-2.6,10-5.6,15.2c-3,5.2-6.7,9.6-10.3,12.4C19.7,43.5,17.2,44.6,15.1,44.6z M32.9,5.4	c-1.6,0-3.7,0.9-6,2.7c-3.4,2.7-6.9,6.9-9.8,11.9l0,0c-6.3,10.9-6.9,20.3-3.6,22.2c1.7,1,4.5,0.1,7.6-2.3c3.4-2.7,6.9-6.9,9.8-11.9	c2.9-5,4.8-10.1,5.4-14.4c0.5-4-0.1-6.8-1.8-7.8C34,5.6,33.5,5.4,32.9,5.4z"></path><path fill="#80deea" d="M33,44.6c-5,0-12.2-6.1-17.6-15.6C8.9,17.8,7.6,6.9,12.5,4.1l0,0C17.4,1.3,26.2,7.8,32.7,19	c3,5.2,5,10.6,5.6,15.2c0.7,4.9-0.3,8.3-2.8,9.8C34.7,44.4,33.9,44.6,33,44.6z M13.5,5.8c-3.3,1.9-2.7,11.3,3.6,22.2	c6.3,10.9,14.1,16.1,17.4,14.2c1.7-1,2.3-3.8,1.8-7.8c-0.6-4.3-2.5-9.4-5.4-14.4C24.6,9.1,16.8,3.9,13.5,5.8L13.5,5.8z"></path><circle cx="24" cy="24" r="4" fill="#80deea"></circle>
                                            </svg>
                                        </div>
                                            <span class="font-medium">{{ $contact->name }}</span>
                                    </div>
                                </td>

                                <td class="py-3 px-6 text-left">
                                    <div class="flex items-center">
                                        <span>{{ $contact->email }}</span>
                                    </div>
                                </td>

                                <td class="py-3 px-6 text-left">
                                    <div class="flex items-center">
                                        <span>{{ $contact->number }}</span>
                                    </div>
                                </td>

                                <td class="py-3 px-6 text-left">
                                    <div class="flex items-center">
                                        <span>{{ $contact->message }}</span>
                                    </div>
                                </td>

                                <td class="py-3 px-6 text-center">
                                    <div class="flex item-center justify-center">

                                        <form action="{{ route('contact.delete', [$contact->id]) }}" method="post">
                                            @csrf
                                            @method('DELETE')

                                            <button class="outline-none border-none" type="submit">
                                                <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                    </svg>
                                                </div>

                                            </button>
                                        </form>


                                    </div>
                                </td>
                            </tr>

                            @endforeach



                        </tbody>
                    </table>
                </div>


            </div>
        </div>
    </div>
</x-app-layout>

resources/views/dashboard/saucecreate.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">


                        <div class="w-full bg-white rounded shadow-lg p-8 m-4">
                          <h1 class="text-3xl font-bold text-lg block w-full text-center text-grey-darkest mb-6">Voeg een saus toe</h1>

                          <form class="mb-4" action="{{ route('sauce.store') }}" method="POST" enctype="multipart/form-data">

                            @csrf
                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="title">Saus Titel</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="text" name="title">
                            </div>
                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="price">Prijs</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="text" name="price">
                            </div>
                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="description">Omschrijving</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="text" name="description">
                            </div>
                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="ingredients">Ingredienten</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="text" name="ingredients">
                            </div>
                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="extra_information">Extra Informatie</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="text" name="extra_information">
                            </div>
                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="image">Afbeelding</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="file" name="image">
                            </div>
                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="bannerimage">Banner Image</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="file" name="bannerimage">
                            </div>

                            <button type="submit" class="w-full h-12 px-6 text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800">Voeg saus toe</button>
                          </form>

                        </div>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/dashboard/sauceedit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">


                        <div class="w-full bg-white rounded shadow-lg p-8 m-4">
                          <h1 class="text-3xl font-bold text-lg block w-full text-center text-grey-darkest mb-6">Pas een saus aan</h1>

                          <form class="mb-4" action="{{ route('sauce.update', [$sauce->id]) }}" method="POST" enctype="multipart/form-data">

                            @csrf

                            @method('put')
                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="title">Saus Titel</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="text" value="{{ $sauce->title }}" name="title">
                            </div>
                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="price">Prijs</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="text" value="{{ $sauce->price }}" name="price">
                            </div>
                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="description">Omschrijving</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="text" value="{{ $sauce->description }}" name="description">
                            </div>
                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="ingredients">Ingredienten</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="text" {{ $sauce->ingredients }} name="ingredients">
                            </div>
                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="extra_information">Extra Informatie</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="text" value="{{ $sauce->extra_information }}" name="extra_information">
                            </div>
                            <div class="flex flex-col mb-4">
                              <label class="mb-2 font-bold text-lg text-grey-darkest" for="image">Afbeelding</label>
                              <input class="border py-2 px-3 text-grey-darkest" type="file" value="{{ $sauce->image }}" name="image">
                            </div>
                            <div class="flex flex-col mb-4">
                                <label class="mb-2 font-bold text-lg text-grey-darkest" for="bannerimage">Banner Image</label>
                                <input class="border py-2 px-3 text-grey-darkest" type="file" name="bannerimage">
                            </div>

                            <button type="submit" class="w-full h-12 px-6 text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800">Saus Aanpassen</button>
                          </form>

                        </div>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/dashboard/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

                <div class="p-6 bg-white border-b border-gray-200">
                    <h1 class="font-bold text-4xl"><span class="font-thin">Verander de content van block </span>{{ $block->block_number }}</h1>
                </div>
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route('block.update', [$block->id]) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <textarea name="content" id="content" cols="30" rows="10">{{ $block->content }}</textarea>

                        <button type="submit" class="w-full h-12 px-6 text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800">Block Aanpassen</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.tiny.cloud/1/ggfv0r19pczlr5yajezco0uoi1a592u0xkpohcwt9znac63k/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: '#content',
        })
    </script>
</x-app-layout>